### ISSUE TITLE
Create the Home page for this Website

### ISSUE THREAD

**Issue by Dipit12** [Dipit12/Marvel-Portal#1]

**Comment by rnihesh** [comment]
assign me , can you say , how can i design the home page, i'll do it as soon as possible !

**Comment by rnihesh** [comment]
yeah, i'll check into it, but , can you describe me or gimme an example like how should it look ?, i'll match the comic's color scheme

**Comment by Dipit12** [comment]
<img width="1709" alt="image" src="https://github.com/user-attachments/assets/61f4774d-dc7b-455a-945b-f7076675f4bb">
It should look somewhat similar to Marvel's official website, like the color scheme should match that
Website: https://www.marvel.com/

**Comment by Dipit12** [comment]
Hi @rnihesh , i have unassigned you from the project, after discussion with other Owners of the project, we have decided to remove this project from open-source and we ourselves would continue with the project

**Comment by rnihesh** [comment]
i made the project 🥲

**Comment by Dipit12** [comment]
Send the screen recording of how the website looks like, lemme see what I can do

**Comment by rnihesh** [comment]
if there is anything you want me to update, i'll do it, please assign me , so that i can complete hacktoberfest2024 badge collection
https://github.com/user-attachments/assets/35213bbf-a417-4cc5-8f8c-eb481fd272dd

if you are interested, i will also make login/signup page

**Comment by rnihesh** [comment]
can u add me as assigne

**Comment by Dipit12** [comment]
Done
